import type { ChartData } from '@tuvi/core';
import { COLORS } from '../colors.js';
import { FONT, type Doc } from '../render.js';

export function renderCover(doc: Doc, chart: ChartData): void {
  const { width, height } = doc.page;

  // Dark background
  doc.save();
  doc.rect(0, 0, width, height).fill(COLORS.coverBg);

  // Ornamental gold borders
  doc.lineWidth(2).strokeColor(COLORS.gold);
  doc.rect(30, 30, width - 60, height - 60).stroke();
  doc.lineWidth(0.5).strokeColor(COLORS.goldLight);
  doc.rect(40, 40, width - 80, height - 80).stroke();

  // Top badge
  doc.fillColor(COLORS.gold).font(FONT.bold).fontSize(14);
  doc.text('◆  TỬ VI ĐẨU SỐ  ◆', 0, 110, { align: 'center', width });

  // Subtitle
  doc.fillColor(COLORS.goldLight).font(FONT.regular).fontSize(11);
  doc.text('Luận giải lá số chi tiết', 0, 135, { align: 'center', width });

  // Divider
  doc.moveTo(width / 2 - 80, 175).lineTo(width / 2 + 80, 175).lineWidth(1).strokeColor(COLORS.gold).stroke();

  // Person name
  doc.fillColor(COLORS.gold).font(FONT.bold).fontSize(28);
  const name = chart.info.name || 'Đương Số';
  doc.text(name.toUpperCase(), 0, 210, { align: 'center', width });

  // Gender + zodiac line
  doc.fillColor(COLORS.goldLight).font(FONT.regular).fontSize(13);
  const genderLabel = chart.info.gender === 'male' ? 'Nam' : 'Nữ';
  doc.text(`${genderLabel}  •  Tuổi ${chart.zodiac}  •  Ngũ hành cục: ${chart.fiveElementsClass}`, 0, 260, {
    align: 'center',
    width,
  });

  // Info block
  const boxTop = 330;
  const boxLeft = 80;
  const boxWidth = width - 160;

  doc.save();
  doc.lineWidth(0.5).strokeColor(COLORS.gold);
  doc.rect(boxLeft, boxTop, boxWidth, 220).stroke();
  doc.restore();

  const rows: Array<[string, string]> = [
    ['Ngày sinh dương', chart.solarDate],
    ['Ngày sinh âm', chart.lunarDate],
    ['Can chi', chart.chineseDate],
    ['Giờ sinh', `${chart.time}  (${chart.timeRange})`],
    ['Nơi sinh', chart.info.birthPlace || '—'],
    ['Mệnh chủ', chart.soul],
    ['Thân chủ', chart.body],
  ];

  const rowH = 28;
  rows.forEach((row, i) => {
    const y = boxTop + 18 + i * rowH;
    doc.fillColor(COLORS.goldLight).font(FONT.regular).fontSize(10);
    doc.text(row[0].toUpperCase(), boxLeft + 20, y, { width: 140 });
    doc.fillColor(COLORS.white).font(FONT.bold).fontSize(12);
    doc.text(row[1], boxLeft + 170, y - 2, { width: boxWidth - 190 });
  });

  // Bottom stamp
  doc.fillColor(COLORS.gold).font(FONT.bold).fontSize(11);
  doc.text('✦  Generated by TỬ VI ĐẨU SỐ AI  ✦', 0, height - 90, { align: 'center', width });
  doc.fillColor(COLORS.goldLight).font(FONT.regular).fontSize(9);
  const now = new Date().toLocaleDateString('vi-VN');
  doc.text(`Ngày lập lá số: ${now}`, 0, height - 70, { align: 'center', width });

  doc.restore();
}
